// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwhUCM6ozxugXln0dONpq_Lm3MSGQO-kQ',
    appId: '1:830408044396:android:1bcc0089a1d19f2426cd49',
    messagingSenderId: '830408044396',
    projectId: 'nextmind-proj',
    storageBucket: 'nextmind-proj.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHx5tx7tcMw_tW2HX1kwKDs4kj3sStbfU',
    appId: '1:830408044396:web:67261e20d603a33e26cd49',
    messagingSenderId: '830408044396',
    projectId: 'nextmind-proj',
    authDomain: 'nextmind-proj.firebaseapp.com',
    storageBucket: 'nextmind-proj.firebasestorage.app',
    measurementId: 'G-EF8CR1SRQN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiSIznXMi3zkXmVyRnCkagID1CVwBIwLA',
    appId: '1:395397021008:ios:e56d6fb5c727fce15b8055',
    messagingSenderId: '395397021008',
    projectId: 'nextmind-v3',
    storageBucket: 'nextmind-v3.firebasestorage.app',
    iosClientId: '395397021008-3v0debq7iglbd11u6f21c34igruhun69.apps.googleusercontent.com',
    iosBundleId: 'com.nextmind.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSIznXMi3zkXmVyRnCkagID1CVwBIwLA',
    appId: '1:395397021008:ios:e56d6fb5c727fce15b8055',
    messagingSenderId: '395397021008',
    projectId: 'nextmind-v3',
    storageBucket: 'nextmind-v3.firebasestorage.app',
    iosClientId: '395397021008-3v0debq7iglbd11u6f21c34igruhun69.apps.googleusercontent.com',
    iosBundleId: 'com.nextmind.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOMX4I4zAULVp0xb4feVGQL19jX4vq1Xc',
    appId: '1:395397021008:web:1657d5198bf77a4d5b8055',
    messagingSenderId: '395397021008',
    projectId: 'nextmind-v3',
    authDomain: 'nextmind-v3.firebaseapp.com',
    storageBucket: 'nextmind-v3.firebasestorage.app',
  );

}