// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/app/appointments/all_psychologists',
    parent: '/app',
    uri: Uri.parse('/app/appointments/all_psychologists'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: '/app/appointments/appointment_confirmation',
    parent: '/app',
    uri: Uri.parse('/app/appointments/appointment_confirmation'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: '/app/appointments/appointment_home',
    parent: '/app',
    uri: Uri.parse('/app/appointments/appointment_home'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: '/app/appointments/psychologist_profile',
    parent: '/app',
    uri: Uri.parse('/app/appointments/psychologist_profile'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(key: '/app', uri: Uri.parse('/app'), routeBuilder: b4Builder),
  RouteEntity(
    key: '/app/chat',
    parent: '/app',
    uri: Uri.parse('/app/chat'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: '/app/chat/contact_search',
    parent: '/app',
    uri: Uri.parse('/app/chat/contact_search'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(
    key: '/app/chat/conversation',
    parent: '/app',
    uri: Uri.parse('/app/chat/conversation'),
    routeBuilder: b22Builder,
  ),
  RouteEntity(
    key: '/app/home',
    parent: '/app',
    uri: Uri.parse('/app/home'),
    routeBuilder: b7Builder,
  ),
  RouteEntity(
    key: '/app/settings/feedback',
    parent: '/app',
    uri: Uri.parse('/app/settings/feedback'),
    routeBuilder: b8Builder,
  ),
  RouteEntity(
    key: '/app/settings/help_central',
    parent: '/app',
    uri: Uri.parse('/app/settings/help_central'),
    routeBuilder: b9Builder,
  ),
  RouteEntity(
    key: '/app/settings/language',
    parent: '/app',
    uri: Uri.parse('/app/settings/language'),
    routeBuilder: b10Builder,
  ),
  RouteEntity(
    key: '/app/settings/legal_information',
    parent: '/app',
    uri: Uri.parse('/app/settings/legal_information'),
    routeBuilder: b11Builder,
  ),
  RouteEntity(
    key: '/app/settings/notifications',
    parent: '/app',
    uri: Uri.parse('/app/settings/notifications'),
    routeBuilder: b12Builder,
  ),
  RouteEntity(
    key: '/app/settings/security',
    parent: '/app',
    uri: Uri.parse('/app/settings/security'),
    routeBuilder: b13Builder,
  ),
  RouteEntity(
    key: '/app/settings/software_information',
    parent: '/app',
    uri: Uri.parse('/app/settings/software_information'),
    routeBuilder: b14Builder,
  ),
  RouteEntity(
    key: '/app/settings/user_account',
    parent: '/app',
    uri: Uri.parse('/app/settings/user_account'),
    routeBuilder: b15Builder,
  ),
  RouteEntity(
    key: '/app/settings',
    parent: '/app',
    uri: Uri.parse('/app/settings'),
    routeBuilder: b16Builder,
  ),
  RouteEntity(
    key: '/auth/forgot_password',
    uri: Uri.parse('/auth/forgot_password'),
    routeBuilder: b17Builder,
  ),
  RouteEntity(
    key: '/auth/signin',
    uri: Uri.parse('/auth/signin'),
    routeBuilder: b18Builder,
  ),
  RouteEntity(
    key: '/auth/signup',
    uri: Uri.parse('/auth/signup'),
    routeBuilder: b19Builder,
  ),
  RouteEntity(
    key: '/not_found',
    uri: Uri.parse('/not_found'),
    routeBuilder: b20Builder,
  ),
  RouteEntity(
    key: '/splash',
    uri: Uri.parse('/splash'),
    routeBuilder: b21Builder,
  ),
];

const routePaths = (
  path: '/',
  app: (
    path: '/app',
    appointments: (
      path: '/app/appointments',
      allPsychologists: '/app/appointments/all_psychologists',
      appointmentConfirmation: '/app/appointments/appointment_confirmation',
      appointmentHome: '/app/appointments/appointment_home',
      psychologistProfile: '/app/appointments/psychologist_profile',
    ),
    chat: (
      path: '/app/chat',
      contactSearch: '/app/chat/contact_search',
      conversation: '/app/chat/conversation',
    ),
    home: '/app/home',
    settings: (
      path: '/app/settings',
      feedback: '/app/settings/feedback',
      helpCentral: '/app/settings/help_central',
      language: '/app/settings/language',
      legalInformation: '/app/settings/legal_information',
      notifications: '/app/settings/notifications',
      security: '/app/settings/security',
      softwareInformation: '/app/settings/software_information',
      userAccount: '/app/settings/user_account',
    ),
  ),
  auth: (
    path: '/auth',
    forgotPassword: '/auth/forgot_password',
    signin: '/auth/signin',
    signup: '/auth/signup',
  ),
  notFound: '/not_found',
  splash: '/splash',
);
